version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - switstigpty
  front:
    build:
      context: ./appli_test
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - switstigpty
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - front
    networks:
      - switstigpty
networks:
  switstigpty:
    driver: bridge
